version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: paper_analyzer_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - paper_network

  # MongoDB (Session Memory)
  mongodb:
    image: mongo:7
    container_name: paper_analyzer_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - paper_network

volumes:
  qdrant_data:
  mongo_data:


networks:
  paper_network:
    driver: bridge
